[package]
name = "demo"
version = "1.0.0"

[addresses]
self = "0x574a3d9f27ff53549c9551d90344bb5b592e1aa7d5a11ae5ebdcb30fdb31a204"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.6.2"
subdir = "aptos-move/framework/aptos-framework"
