[package]
name = "demo"
version = "1.0.0"

[addresses]
self = "0x3c07159ac67e43f7b2b326dd41d3d457530ceb4c661eaf49e3b1c88ae457ee39"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.6.2"
subdir = "aptos-move/framework/aptos-framework"
