[package]
name = "hello_blockchain"
version = "1.0.0"

[addresses]
hello_blockchain = "0xb3e5e9d58797efbce688894c9aebf09afb074d9c03201b452bc81e8afcd4a75d"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "6c48e2d56573282ae9835829a774e691f5c1c663"
subdir = "aptos-move/framework/aptos-framework"
