[package]
name = "demo111"
version = "1.0.0"

[addresses]
self = "0xb3e5e9d58797efbce688894c9aebf09afb074d9c03201b452bc81e8afcd4a75d"
pancake = "0xc7efb4076dbe143cbcd98cfaaa929ecfc8f299203dfff63b95ccb6bfe19850fa"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core", rev = "6c48e2d56573282ae9835829a774e691f5c1c663", subdir = "aptos-move/framework/aptos-framework" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core", rev = "6c48e2d56573282ae9835829a774e691f5c1c663", subdir = "aptos-move/framework/aptos-stdlib" }
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core", rev = "6c48e2d56573282ae9835829a774e691f5c1c663", subdir = "aptos-move/framework/move-stdlib" }
